services:

    postgres:
      image: 'postgres:17.2'
      environment:
        - 'POSTGRES_DB=postgres_db'
        - 'POSTGRES_PASSWORD=password'
        - 'POSTGRES_USER=admin'
      volumes:
        - ./volumes/pg_data:/var/lib/postgresql/data
      container_name: postgres-db-cnr
      ports:
        - '5432:5432'

#    pgadmin:
#      image: dpage/pgadmin4:9.3
#      environment:
#        - 'PGADMIN_DEFAULT_EMAIL=admin@admin.admin'
#        - 'PGADMIN_DEFAULT_PASSWORD=admin'
#      restart: always
#      container_name: pgadmin-cnr
#      ports:
#        - '8081:80'
#      depends_on:
#        - postgres


    mongo:
      image: mongo:8.0
      #image: mongo
      container_name: mongo-db-cnr
      restart: always
      ports:
        - '27017:27017'
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: secret
      volumes:
        - ./volumes/mongo_data/:/data/db/
        - /etc/timezone:/etc/timezone:ro

    mongo-express:
      image: mongo-express
      container_name: mongo-express-ui-cnr
      restart: always
      ports:
        - '8081:8081'
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: secret
        ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongo:27017/
  #      ME_CONFIG_MONGODB_SERVER: mongo
  #      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongo:27017/
  #      mongodb://admin:secret@localhost:27017/?authSource=admin
        ME_CONFIG_BASICAUTH: false
      depends_on:
          - 'mongo'

##volumes:
##  mongo-data: